// frontend/src/pages/PlanDetails.tsx
import React, { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

interface CalculationResult {
    month: number;
    amount: number;
    commission: number;
    amountGiven: number;
}

const PlanDetails: React.FC = () => {
    const { user } = useAuth();
    const location = useLocation();
    const { results, totalProfit, groupId } = location.state || { results: [], totalProfit: null, groupId: null };
    const [buttonLabel, setButtonLabel] = useState('Join');
    console.log('User Role:', user?.userRole);

    const handleJoinGroup = async (userId: string) => {
        if (!user || !userId || !groupId) return;

        try {
            const response = await fetch('http://localhost:3000/api/groups/request', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${localStorage.getItem('authToken')}`,
                },
                body: JSON.stringify({
                    groupId: groupId,
                    userId: userId,
                }),
            });

            if (!response.ok) {
                throw new Error('Failed to join group');
            }

            const data = await response.json();
            console.log('Successfully joined group:', data);
            setButtonLabel('Request Sent Successfully');
            // Optionally, add any success feedback or redirection here
        } catch (error) {
            console.error('Error joining group:', error);
            setButtonLabel('Join');
            // Handle error feedback here
        }
    }

    return (
        <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-blue-100 to-green-100 py-10 px-4">
            <div className="w-full max-w-4xl bg-white p-6 rounded-lg shadow-md">
                <h2 className="text-3xl font-bold text-center mb-6 text-black-600">Chit Calculation Results</h2>
                {user?.userRole === 'participant' && (
                    <div className="flex justify-end mb-4">
                        <button
                            onClick={() => handleJoinGroup(user.userId)}
                            className="bg-indigo-800 text-white font-bold py-2 px-4 rounded"
                        >
                            {buttonLabel}
                        </button>
                    </div>
                )}
                <table className="min-w-full bg-white border rounded-lg text-center">
                    <thead>
                        <tr>
                            <th className="py-2 px-4 border-b">Month</th>
                            <th className="py-2 px-4 border-b">Amount</th>
                            <th className="py-2 px-4 border-b">Commission</th>
                            <th className="py-2 px-4 border-b">Amount Given</th>
                        </tr>
                    </thead>
                    <tbody>
                        {results.map((result: CalculationResult, index: number) => (
                            <tr key={index}>
                                <td className="py-2 px-4 border-b text-center">{`Month ${result.month}`}</td>
                                <td className="py-2 px-4 border-b text-center">${result.amount}</td>
                                <td className="py-2 px-4 border-b text-center">${result.commission}</td>
                                <td className="py-2 px-4 border-b text-center">${result.amountGiven}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {user !== null ? (
                    totalProfit !== null ? (
                        <div className="mt-4 text-lg font-semibold text-center">
                            Total Profit: ${totalProfit.toFixed(2)}
                        </div>
                    ) : null
                ) : (
                    <Link to='/login'>
                    <div className="mt-4 text-lg font-semibold text-center hover:underline">
                        Log In to Join Group
                    </div>
                    </Link>
                )}

            </div>
        </div>
    );
};

export default PlanDetails;

// frontend-ang/src/app/plan-details/plan-details.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-plan-details',
  imports:[CommonModule],
  templateUrl: './plan-details.component.html',
  styleUrls: ['./plan-details.component.css'],
})
export class PlanDetailsComponent implements OnInit {
  results: any[] = [];
  totalProfit: number = 0; // Initialize with a default value
  groupId: string | null = null;

  constructor(private router: Router) {}

  ngOnInit(): void {
    const state = history.state;

    if (state && state.results && state.totalProfit !== undefined && state.groupId) {
      this.results = state.results;
      this.totalProfit = state.totalProfit || 0; // Default to 0 if null
      this.groupId = state.groupId;
    } else {
      console.error('No state received.');
      this.router.navigate(['/chitplans']); // Redirect if no state is received
    }
  }

  handleJoinGroup(): void {
    if (!this.groupId) {
      console.error('Group ID is missing.');
      return;
    }

    const userId = localStorage.getItem('userId');
    if (!userId) {
      console.error('User ID is missing.');
      return;
    }

    fetch('http://localhost:3000/api/groups/request', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${localStorage.getItem('authToken')}`,
      },
      body: JSON.stringify({
        groupId: this.groupId,
        userId: userId,
      }),
    })
      .then((response) => {
        if (!response.ok) {
          throw new Error('Failed to join group');
        }
        return response.json();
      })
      .then((data) => {
        console.log('Successfully joined group:', data);
        alert('Request Sent Successfully');
      })
      .catch((error) => {
        console.error('Error joining group:', error);
      });
  }
}

<div class="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-blue-100 to-green-100 py-10 px-4">
    <div class="w-full max-w-4xl bg-white p-6 rounded-lg shadow-md">
      <h2 class="text-3xl font-bold text-center mb-6 text-black-600">
        Chit Calculation Results
      </h2>
  
      <!-- Join Button -->
      <div class="flex justify-end mb-4" *ngIf="groupId">
        <button
          (click)="handleJoinGroup()"
          class="bg-indigo-800 text-white font-bold py-2 px-4 rounded"
        >
          Join
        </button>
      </div>
  
      <!-- Results Table -->
      <table class="min-w-full bg-white border rounded-lg text-center">
        <thead>
          <tr>
            <th class="py-2 px-4 border-b">Month</th>
            <th class="py-2 px-4 border-b">Amount</th>
            <th class="py-2 px-4 border-b">Commission</th>
            <th class="py-2 px-4 border-b">Amount Given</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let result of results; let i = index">
            <td class="py-2 px-4 border-b text-center">Month {{ result.month }}</td>
            <td class="py-2 px-4 border-b text-center">${{ result.amount }}</td>
            <td class="py-2 px-4 border-b text-center">${{ result.commission }}</td>
            <td class="py-2 px-4 border-b text-center">${{ result.amountGiven }}</td>
          </tr>
          <tr *ngIf="!results || results.length === 0">
            <td colspan="4" class="py-4 text-center text-gray-500">
              No data available.
            </td>
          </tr>
        </tbody>
      </table>
  
      <!-- Total Profit -->
      <div
        *ngIf="totalProfit !== null"
        class="mt-4 text-lg font-semibold text-center"
      >
        Total Profit: ${{ totalProfit.toFixed(2) }}
      </div>
    </div>
  </div>
