// frontend/src/pages/GroupForm.tsx
import React, { useState } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';

const GroupForm: React.FC = () => {

    const [formData, setFormData] = useState({
        groupId: '',
        groupName: '',
        members: '',
        totalAmount: '',
        interest: '',
        organizerId: '',
        groupType: '',
        duration: '',
        ticketValue: '',
        description: '',
    });

    const { user, setUser } = useAuth(); // Access user data from context
    const navigate = useNavigate();
    // Check if the user is an organizer
    if (user?.userRole !== 'organizer') {
        return <div className="text-center text-red-500">You do not have permission to access this page.</div>;
    }

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {

        const { name, value } = e.target;

        setFormData((prevData) => ({ ...prevData, [name]: value, }));

    };

    const handleSubmit = async (e: React.FormEvent) => {

        e.preventDefault();

        try {
            formData.ticketValue = formData.members && formData.members
                ? (parseFloat(formData.totalAmount) / parseInt(formData.members)).toFixed(2)
                : '0.00';

            formData.organizerId = user.userId;
            formData.duration = formData.members;

            const response = await axios.post('http://localhost:3000/api/groups', formData, {
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${localStorage.getItem('authToken')}`,
                },
            }
            );
            const User = await axios.patch(`http://localhost:3000/api/users/addGroup/${user.userEmail}`, {
                "groupId": `${formData.groupId}`
            }, {
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${localStorage.getItem('authToken')}`,
                },
            },)
            setUser(User.data);
            console.log('Group created successfully:', response.data,User.data);
            navigate('/mygroups'); // Redirect to groups page after creating a new group

        } catch (error) {
            if (axios.isAxiosError(error)) {
                console.error('Error creating group:', error.response?.data || error.message);
            } else {
                console.error('Unexpected error:', error);
            }
        }
    };

    return (

        <form onSubmit={handleSubmit} className="max-w-3xl mx-auto p-6 bg-white shadow-md rounded-lg space-y-4">

            <h2 className="text-2xl font-semibold text-center">Group Details</h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

                <input type="text"

                    name="groupId"

                    placeholder="Enter group Id"

                    value={formData.groupId}

                    onChange={handleChange}

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />


                <input type="text"

                    name="groupName"

                    placeholder="Enter group name"

                    value={formData.groupName}

                    onChange={handleChange}

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />

                <input type="number"

                    name="members"

                    placeholder="Enter number of members"

                    value={formData.members}

                    onChange={handleChange}

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />

                <input type="number"

                    name="totalAmount"

                    placeholder="Enter total amount"

                    value={formData.totalAmount}

                    onChange={handleChange}

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />

                <input type="text"

                    name="interest"

                    placeholder="Enter group interest"

                    value={formData.interest}

                    onChange={handleChange}

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />

                {/* <input type="text"

                    name="organizerId"

                    placeholder="Enter organizer ID"

                    value={formData.organizerId}

                    onChange={handleChange}

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" /> */}

                <input type="text"

                    name="groupType"

                    placeholder="Enter group type"

                    value={formData.groupType}

                    onChange={handleChange}

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />

                <input type="text"

                    name="duration"

                    placeholder="Enter duration"

                    value={formData.members}

                    readOnly

                    className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />

                <input type="number"
                    name="ticketValue"
                    placeholder="Ticket Value (calculated)"
                    value={formData.members && formData.members
                        ? (parseFloat(formData.totalAmount) / parseInt(formData.members)).toFixed(2)
                        : '0.00'}
                    readOnly // Make it read-only since it's calculated
                    className="w-full p-2 border border-gray-300 rounded-md bg-gray-100" />
            </div>

            <textarea name="description"

                placeholder="Enter group description"

                value={formData.description}

                onChange={handleChange}

                className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />

            <button type="submit"
                className="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition duration-200">
                Save </button>
        </form>
    );
};

export default GroupForm;

// frontend-ang/src/app/group-form/group-form.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { HttpClient, HttpHeaders } from '@angular/common/http';
import { BehaviorSubject } from 'rxjs';
import { AuthService } from '../../auth/auth.service';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-group-form',
  imports:[CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './group-form.component.html',
  styleUrls: ['./group-form.component.css'],
})
export class GroupFormComponent implements OnInit {
  formData = {
    groupId: '',
    groupName: '',
    members: '',
    totalAmount: '',
    interest: '',
    organizerId: '',
    groupType: '',
    duration: '',
    ticketValue: '',
    description: 'Join Group',
  };

  user: any;
  error: string | null = null;

  constructor(
    private http: HttpClient,
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.authService.user$.subscribe((user) => {
      this.user = user;
      if (this.user?.userRole !== 'organizer') {
        this.error = 'You do not have permission to access this page.';
      }
    });
    // Check if user is logged in
    if (!this.authService.isAuthenticated()) {
      this.error = 'You must be logged in to create a group.';
    }
  }

  handleChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    const { name, value } = target;
  
    // Ensure name exists in formData and update it
    if (name in this.formData) {
      this.formData[name as keyof typeof this.formData] = value;
    }
  }
  
  

  handleSubmit(event: Event): void {
    event.preventDefault();

    if (!this.user) {
      this.error = 'You must be logged in to create a group.';
      return;
    }

    if (this.formData.members) {
      this.formData.ticketValue = (parseFloat(this.formData.totalAmount) / parseInt(this.formData.members)).toFixed(2);
    } else {
      this.formData.ticketValue = '0.00';
    }

    this.formData.organizerId = this.user.userId;
    this.formData.duration = this.formData.members;

    const headers = new HttpHeaders({
      'Content-Type': 'application/json',
      Authorization: `Bearer ${this.authService.getToken()}`,
    });

    this.http
      .post('http://localhost:3000/api/groups', this.formData, { headers })
      .subscribe(
        (response: any) => {
          this.http
            .patch(`http://localhost:3000/api/users/addGroup/${this.user.userEmail}`, {
              groupId: this.formData.groupId,
            }, { headers })
            .subscribe((userResponse: any) => {
              this.authService.userSubject.next(userResponse.data);
              this.router.navigate(['/mygroups'], { queryParams: { refresh: 'true' } });
            });
        },
        (error) => {
          console.error('Error creating group:', error);
        }
      );
  }

  formatTicketValue(): string {
    return this.formData.members ? (parseFloat(this.formData.totalAmount) / parseInt(this.formData.members)).toFixed(2) : '0.00';
  }

}

<div class="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-blue-100 to-green-100 py-10 px-4">
    <div class="w-full max-w-4xl bg-white p-6 rounded-lg shadow-md">
      <h2 class="text-2xl font-semibold text-center mb-6 text-gray-800">Group Details</h2>
  
      <div *ngIf="error" class="text-red-500 mb-4 text-center">{{ error }}</div>
  
      <form (ngSubmit)="handleSubmit($event)" class="space-y-4">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
  
          <input type="text"
                 name="groupId"
                 placeholder="Enter group Id"
                 [(ngModel)]="formData.groupId"
                 (ngModelChange)="handleChange($event)"
                 class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
  
          <input type="text"
                 name="groupName"
                 placeholder="Enter group name"
                 [(ngModel)]="formData.groupName"
                 (ngModelChange)="handleChange($event)"
                 class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
  
          <input type="number"
                 name="members"
                 placeholder="Enter number of members"
                 [(ngModel)]="formData.members"
                 (ngModelChange)="handleChange($event)"
                 class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
  
          <input type="number"
                 name="totalAmount"
                 placeholder="Enter total amount"
                 [(ngModel)]="formData.totalAmount"
                 (ngModelChange)="handleChange($event)"
                 class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
  
          <input type="text"
                 name="interest"
                 placeholder="Enter group interest"
                 [(ngModel)]="formData.interest"
                 (ngModelChange)="handleChange($event)"
                 class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
  
          <input type="text"
                 name="groupType"
                 placeholder="Enter group type"
                 [(ngModel)]="formData.groupType"
                 (ngModelChange)="handleChange($event)"
                 class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
  
          <input type="text"
                 name="duration"
                 placeholder="Enter duration"
                 [value]="formData.members"
                 readOnly
                 class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" />
  
          <input type="number"
                 name="ticketValue"
                 placeholder="Ticket Value (calculated)"
                 [value]="formatTicketValue()"
                 readOnly
                 class="w-full p-3 border border-gray-300 rounded-md bg-gray-100" />
  
        </div>
  
        <textarea name="description"
                  placeholder="Enter group description"
                  [(ngModel)]="formData.description"
                  (ngModelChange)="handleChange($event)"
                  class="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"></textarea>
  
        <button type="submit"
                class="w-full bg-blue-600 text-white py-3 rounded-md hover:bg-blue-700 transition duration-200">
          Save
        </button>
      </form>
    </div>
  </div>
