// frontend-ang/src/app/group-transactions/group-transactions.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { CommonModule, DatePipe } from '@angular/common';  // Import DatePipe

interface Transaction {
  transactionId: string;
  transactionAmount: number;
  transactionDate: string;
  transactionType: string;
  transactionFrom: string;
  transactionTo: string;
}

@Component({
  selector: 'app-group-transactions',
  imports:[CommonModule],
  standalone: true,  // Mark the component as standalone
  templateUrl: './group-transactions.component.html',
  styleUrls: ['./group-transactions.component.css'],
  providers: [DatePipe]  // Provide DatePipe locally
})
export class GroupTransactionsComponent implements OnInit {
  groupId: string | null = null;
  transactions: Transaction[] = [];
  filteredTransactions: Transaction[] = [];
  userNames: { [key: string]: string } = {};
  error: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private http: HttpClient,
    private datePipe: DatePipe  // Inject DatePipe
  ) {}

  ngOnInit(): void {
    this.groupId = this.route.snapshot.paramMap.get('groupId');
    if (this.groupId) {
      this.fetchTransactions(this.groupId);
    }
  }

  fetchTransactions(groupId: string): void {
    const authToken = localStorage.getItem('authToken');
    const headers = new HttpHeaders().set('Authorization', `Bearer ${authToken}`).set('Content-Type', 'application/json');

    this.http.get<Transaction[]>(`http://localhost:3000/api/transactions/find/group/${groupId}`, { headers })
      .subscribe({
        next: (transactionsData) => {
          this.transactions = transactionsData;
          this.filteredTransactions = transactionsData.filter(tx => tx.transactionType === 'debit');
          
          const userIds = [
            ...new Set(
              transactionsData.flatMap(tx => [tx.transactionFrom, tx.transactionTo])
            )
          ];

          this.fetchUserNames(userIds);
        },
        error: (err) => {
          console.error('Error fetching transactions:', err);
          this.error = 'Failed to fetch transactions.';
        }
      });
  }

  fetchUserNames(userIds: string[]): void {
    const authToken = localStorage.getItem('authToken');
    const headers = new HttpHeaders().set('Authorization', `Bearer ${authToken}`).set('Content-Type', 'application/json');

    userIds.forEach(userId => {
      this.http.get<{ userName: string }>(`http://localhost:3000/api/users/${userId}`, { headers })
        .subscribe({
          next: (userData) => {
            this.userNames[userId] = userData.userName;
          },
          error: (err) => {
            console.error('Error fetching user name:', err);
          }
        });
    });
  }

  getMonthName(month: number): string {
    return new Date(0, month - 1).toLocaleString('default', { month: 'long' });
  }

  // Method to format date using DatePipe
  formatDate(date: string): string | null {
    return this.datePipe.transform(date, 'shortDate');
  }

  filterDebits(): void {
    this.filteredTransactions = this.transactions.filter(tx => tx.transactionType === 'debit');
  }

  filterByMonth(month: number): void {
    this.filteredTransactions = this.transactions.filter(tx => 
      tx.transactionType === 'debit' &&
      new Date(tx.transactionDate).getMonth() === month - 1
    );
  }

  // Inside GroupTransactionsComponent
onMonthSelect(event: any): void {
  const selectedMonth = parseInt(event.target.value);
  if (selectedMonth) {
    this.filterByMonth(selectedMonth);
  } else {
    this.filterDebits(); // Show all debits if no specific month is selected
  }
}

}

<div class="flex flex-col items-center justify-center min-h-screen bg-gray-50 py-10 px-4">
    <div class="w-full max-w-4xl bg-white p-8 rounded-lg shadow-md">
      <h2 class="text-3xl font-semibold text-center mb-6 text-blue-600">All Transactions for Group</h2>
  
      <div *ngIf="error" class="text-red-500">{{ error }}</div>
  
      <div class="flex justify-center space-x-4 mb-6">
        <button
          class="bg-red-500 text-white py-2 px-4 rounded-md hover:bg-red-600 transition"
          (click)="filterDebits()"
        >
          Show All
        </button>
  
        <select
          (change)="onMonthSelect($event)"
          class="bg-gray-200 py-2 px-4 rounded-md text-gray-700"
        >
          <option value="">Select Month</option>
          <option *ngFor="let month of [1,2,3,4,5,6,7,8,9,10,11,12]" [value]="month">
            {{ getMonthName(month) }}
          </option>
        </select>
      </div>
  
      <div *ngIf="filteredTransactions.length > 0; else noTransactions" class="overflow-x-auto">
        <table class="min-w-full bg-white rounded-lg shadow-sm">
          <thead>
            <tr class="bg-indigo-200 text-indigo-900">
              <th class="py-4 px-6 border-b text-left">Transaction ID</th>
              <th class="py-4 px-6 border-b text-right">Amount</th>
              <th class="py-4 px-6 border-b text-left">Date</th>
              <th class="py-4 px-6 border-b text-left">Transaction From</th>
              <th class="py-4 px-6 border-b text-left">Transaction To</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let transaction of filteredTransactions" class="hover:bg-indigo-50">
              <td class="py-4 px-6 border-b text-gray-800">{{ transaction.transactionId }}</td>
              <td class="py-4 px-6 border-b text-right text-gray-800">${{ transaction.transactionAmount }}</td>
              <td class="py-4 px-6 border-b text-gray-800">{{ formatDate(transaction.transactionDate) }}</td>
              <td class="py-4 px-6 border-b text-gray-800">{{ userNames[transaction.transactionFrom] || transaction.transactionFrom }}</td>
              <td class="py-4 px-6 border-b text-gray-800">{{ userNames[transaction.transactionTo] || transaction.transactionTo }}</td>
            </tr>
          </tbody>
        </table>
      </div>
  
      <ng-template #noTransactions>
        <div class="text-center text-gray-600">No transactions found.</div>
      </ng-template>
    </div>
  </div>

// frontend/src/pages/GroupTransactions.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';

interface Transaction {
    transactionId: string;
    transactionAmount: number;
    transactionDate: string; // Assuming the date is in ISO string format
    transactionType: string;
    transactionFrom: string; // Add transactionFrom field
    transactionTo: string; // Add transactionTo field
}

const GroupTransactions: React.FC = () => {
    const { groupId } = useParams<{ groupId: string }>();
    const [transactions, setTransactions] = useState<Transaction[]>([]);
    const [filteredTransactions, setFilteredTransactions] = useState<Transaction[]>([]);
    const [userNames, setUserNames] = useState<{ [key: string]: string }>({}); // Store user names by userId
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchTransactions = async () => {
            try {
                const response = await axios.get(`http://localhost:3000/api/transactions/find/group/${groupId}`, {
                    headers: {
                        'Content-Type': 'application/json',
                        Authorization: `Bearer ${localStorage.getItem('authToken')}`,
                    },
                });
                const transactionsData: Transaction[] = response.data;
                setTransactions(transactionsData);
                setFilteredTransactions(
                    transactionsData.filter((tx) => tx.transactionType === 'debit') // Default to debit transactions
                );

                // Collect unique userIds (transactionFrom and transactionTo)
                const userIds = [
                    ...new Set(
                        transactionsData.flatMap((transaction) => [
                            transaction.transactionFrom,
                            transaction.transactionTo,
                        ])
                    ),
                ];

                // Fetch user names for each userId
                const fetchedUserNames: { [key: string]: string } = {};
                for (const userId of userIds) {
                    const userResponse = await axios.get(`http://localhost:3000/api/users/${userId}`, {
                        headers: {
                            'Content-Type': 'application/json',
                            Authorization: `Bearer ${localStorage.getItem('authToken')}`,
                        },
                    });
                    fetchedUserNames[userId] = userResponse.data.userName; // Assuming the API returns userName
                }

                setUserNames(fetchedUserNames); // Set the user names in state
            } catch (err) {
                console.error('Error fetching transactions:', err);
                setError('Failed to fetch transactions.');
            }
        };

        fetchTransactions();
    }, [groupId]);

    // Filter by transaction type (debit)
    const filterDebits = () => {
        setFilteredTransactions(transactions.filter((tx) => tx.transactionType === 'debit'));
    };

    // Filter by month and ensure only debit transactions
    const filterByMonth = (month: number) => {
        setFilteredTransactions(
            transactions.filter(
                (tx) =>
                    tx.transactionType === 'debit' &&
                    new Date(tx.transactionDate).getMonth() === month - 1
            )
        );
    };

    return (
        <div className="flex flex-col items-center justify-center min-h-screen bg-gray-50 py-10 px-4">
            <div className="w-full max-w-4xl bg-white p-8 rounded-lg shadow-md">
                <h2 className="text-3xl font-semibold text-center mb-6 text-blue-600">All Transactions for Group</h2>

                {error && <div className="text-red-500">{error}</div>}

                <div className="flex justify-center space-x-4 mb-6">
                    <button
                        className="bg-red-500 text-white py-2 px-4 rounded-md hover:bg-red-600 transition"
                        onClick={filterDebits}
                    >
                        Show All
                    </button>
                    {/* Add a dropdown for month filter */}
                    <select
                        onChange={(e) => {
                            const selectedMonth = parseInt(e.target.value);
                            if (selectedMonth) {
                                filterByMonth(selectedMonth);
                            } else {
                                filterDebits(); // Show all debits if no specific month is selected
                            }
                        }}
                        className="bg-gray-200 py-2 px-4 rounded-md text-gray-700"
                    >
                        <option value="">Select Month</option>
                        {[...Array(12)].map((_, i) => (
                            <option key={i} value={i + 1}>
                                {new Date(0, i).toLocaleString('default', { month: 'long' })}
                            </option>
                        ))}
                    </select>
                </div>

                {filteredTransactions.length > 0 ? (
                    <div className="overflow-x-auto">
                        <table className="min-w-full bg-white rounded-lg shadow-sm">
                            <thead>
                                <tr className="bg-indigo-200 text-indigo-900">
                                    <th className="py-4 px-6 border-b text-left">Transaction ID</th>
                                    <th className="py-4 px-6 border-b text-right">Amount</th>
                                    <th className="py-4 px-6 border-b text-left">Date</th>
                                    {/* <th className="py-4 px-6 border-b text-left">Type</th> */}
                                    <th className="py-4 px-6 border-b text-left">Transaction From</th>
                                    <th className="py-4 px-6 border-b text-left">Transaction To</th>
                                </tr>
                            </thead>
                            <tbody>
                                {filteredTransactions.map((transaction) => (
                                    <tr key={transaction.transactionId} className="hover:bg-indigo-50">
                                        <td className="py-4 px-6 border-b text-gray-800">{transaction.transactionId}</td>
                                        <td className="py-4 px-6 border-b text-right text-gray-800">${transaction.transactionAmount}</td>
                                        <td className="py-4 px-6 border-b text-gray-800">{new Date(transaction.transactionDate).toLocaleDateString()}</td>
                                        {/* <td className="py-4 px-6 border-b text-gray-800">
                                            <span className="font-semibold px-3 py-1 rounded-full bg-red-200 text-red-800">
                                                {transaction.transactionType}
                                            </span>
                                        </td> */}
                                        <td className="py-4 px-6 border-b text-gray-800">{userNames[transaction.transactionFrom] || transaction.transactionFrom}</td>
                                        <td className="py-4 px-6 border-b text-gray-800">{userNames[transaction.transactionTo] || transaction.transactionTo}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                ) : (
                    <div className="text-center text-gray-600">No transactions found.</div>
                )}
            </div>
        </div>
    );
};

export default GroupTransactions;
