// frontend-ang/src/app/my-groups/my-groups.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Router } from '@angular/router';
import { AuthService } from '../../auth/auth.service';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-my-groups',
  imports:[CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './my-groups.component.html', // Link to the HTML file
  styleUrls: ['./my-groups.component.css'], // Link to the CSS file
})
export class MyGroupsComponent implements OnInit {
  groups: any[] = [];
  error: string | null = null;
  userRole: string | null = null;

  constructor(
    private authService: AuthService,
    private http: HttpClient,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.authService.user$.subscribe((user) => {
      if (user) {
        this.userRole = user.userRole;
        if (user.groupIds.length > 0) {
          this.fetchGroups(user.userEmail, user.groupIds);
        } else {
          this.error = 'No groups found.';
        }
      }
    });
  }

  private fetchGroups(userEmail: string, groupIds: string[]): void {
    const token = this.authService.getToken();
    if (!token) {
      this.error = 'Authentication token is missing.';
      return;
    }

    const headers = new HttpHeaders({
      Authorization: `Bearer ${token}`,
    });

    this.http
      .get<any[]>(`http://localhost:3000/api/users/groups/${userEmail}`, { headers })
      .subscribe({
        next: (response) => {
          console.log('Fetched groups:', response);
          this.groups = response.filter((group) => groupIds.includes(group.groupId));
        },
        error: (err) => {
          console.error('Error fetching groups:', err);
          this.error = 'Failed to fetch groups.';
        },
      });
  }

  handleViewDetails(groupId: string): void {
    this.router.navigate([`/groups/${groupId}`]);
  }

  handleCreateGroup(): void {
    this.router.navigate(['/create-group']);
  }
}

<div class="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-blue-100 to-green-100 py-10 px-4">
  <div class="w-full max-w-4xl bg-white p-6 rounded-lg shadow-md">
    <h2 class="text-3xl font-bold text-center mb-6 text-black-700">My Groups</h2>
    <div *ngIf="error" class="text-red-500 mb-4 text-center">{{ error }}</div>

    <!-- Conditionally render the Create Group button based on user role -->
    <div *ngIf="userRole === 'organizer'" class="flex justify-end mb-4">
      <button
        class="h-12 px-6 bg-green-600 text-white rounded-lg hover:bg-green-500 transition-colors duration-200"
        (click)="handleCreateGroup()"
      >
        Create Group
      </button>
    </div>

    <!-- Groups grid layout -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      <div *ngFor="let group of groups" class="p-4 border rounded-lg shadow hover:shadow-lg transition-shadow duration-200 bg-gray-50 flex flex-col">
        <h3 class="text-xl font-semibold mb-2 text-indigo-900">{{ group.groupName }}</h3>
        <p class="text-gray-700"><strong>Interest:</strong> {{ group.interest }}%</p>
        <p class="text-gray-700"><strong>Members:</strong> {{ group.members }}</p>
        <p class="text-gray-700"><strong>Duration:</strong> {{ group.duration }} months</p>
        <p class="text-gray-700"><strong>Total Amount:</strong> ${{ group.totalAmount }}</p>
        <p class="text-gray-700"><strong>Ticket Value:</strong> ${{ group.ticketValue }}</p>
        <p class="text-gray-700 mb-4 flex-grow">{{ group.description }}</p>
        <div class="flex justify-center mt-auto">
          <button
            class="w-full max-w-xs bg-indigo-800 text-white py-2 px-4 rounded-md hover:bg-indigo-400 transition"
            (click)="handleViewDetails(group.groupId)"
          >
            View Details
          </button>
        </div>
      </div>
    </div>

    <!-- No groups found -->
    <ng-template #noGroups>
      <div class="text-gray-500 text-center">No groups found.</div>
    </ng-template>
  </div>
</div>

// frontend/src/pages/MyGroups.tsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom'; // Import useNavigate
interface Group {
  groupId: string;
  groupName: string;
  groupType: string;
  interest: number;
  organizerId: string;
  members: number;
  duration: number;
  totalAmount: number;
  ticketValue: number;
  participants: string[];
  description: string;
  createdAt: Date;
  updatedAt: Date;
}
const MyGroups: React.FC = () => {
  const { user } = useAuth(); // Access user data from context
  const [groups, setGroups] = useState<Group[]>([]);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate(); // Initialize useNavigate
  useEffect(() => {
    const fetchGroups = async () => {
      if (user && user.groupIds.length > 0) {
        try {
          const response = await axios.get(`http://localhost:3000/api/users/groups/${user?.userEmail}`, {
            headers: {
              'Content-Type': 'application/json',
              Authorization: `Bearer ${localStorage.getItem('authToken')}`,
            },
          });
          const userGroups = response.data.filter((group: Group) =>
            user.groupIds.includes(group.groupId)
          );
          setGroups(userGroups);
        } catch (err) {
          console.error('Error fetching groups:', err);
          setError('Failed to fetch groups.');
        }
      }
    };
    fetchGroups();
  }, [user]);
  const handleViewDetails = (groupId: string) => {
    navigate(`/groups/${groupId}`); // Redirect to the group details page
  };
  const handleCreateGroup = () => {
    navigate('/create-group'); // Redirect to the create group page
  };
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-blue-100 to-green-100">
      <div className="w-full max-w-4xl p-8 bg-white rounded-2xl shadow-lg">
        <h2 className="text-3xl font-bold text-center text-black-800 mb-6">My Groups</h2>
        {error && <div className="text-red-500 mb-4 text-center">{error}</div>}
        {/* Conditionally render the Create Group button based on user role */}
        {user?.userRole === 'organizer' && ( // Check if the user is an organizer
        <div className="flex justify-end mb-4">
          <button
            className="h-12 px-6 bg-green-600 text-white rounded-lg hover:bg-green-500 transition-colors duration-200"
            onClick={handleCreateGroup}
          >
            Create Group
          </button>
        </div>
        )}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {groups.length > 0 ? (
            groups.map(group => (
              <div key={group.groupId} className="flex flex-col p-6 border rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200 bg-gray-50">
                <h3 className="text-xl font-semibold text-indigo-800">{group.groupName}</h3>
                {/* <p className="text-gray-600">Type: <span className="font-medium">{group.groupType}</span></p> */}
                <p className="text-gray-600">Interest: <span className="font-medium">{group.interest}%</span></p>
                <p className="text-gray-600">Members: <span className="font-medium">{group.members}</span></p>
                <p className="text-gray-600">Duration: <span className="font-medium">{group.duration} months</span></p>
                <p className="text-gray-600">Total Amount: <span className="font-bold">${group.totalAmount}</span></p>
                <p className="text-gray-600">Ticket Value: <span className="font-bold">${group.ticketValue}</span></p>
                <p className="text-gray-600 mb-4 flex-grow">{group.description}</p>
                <div className="mt-4">
                  <button
                    className="w-full h-12 bg-indigo-800 text-white rounded-lg hover:bg-indigo-400 transition-colors duration-200"
                    onClick={() => handleViewDetails(group.groupId)}
                  >
                    View Details
                  </button>
                </div>
              </div>
            ))
          ) : (
            <div className="text-gray-500 text-center">No groups found.</div>
          )}
        </div>
      </div>
    </div>
  );
};
export default MyGroups;
