// frontend-ang/src/app/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-profile',
  imports:[CommonModule],
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {
  user: any = null;
  error: string | null = null;

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    const storedUserEmail = localStorage.getItem('userEmail');

    if (storedUserEmail) {
      this.fetchUserDetails(storedUserEmail);
    } else {
      this.error = 'No user email found in localStorage.';
    }
  }

  fetchUserDetails(email: string): void {
    const headers = new HttpHeaders({
      'Content-Type': 'application/json',
      Authorization: `Bearer ${localStorage.getItem('authToken')}`
    });

    this.http.get(`http://localhost:3000/api/users/email/${email}`, { headers })
      .subscribe({
        next: (data) => {
          this.user = data;
        },
        error: (err) => {
          console.error('Error fetching user data:', err);
          this.error = 'Failed to fetch user details.';
        }
      });
  }

  handleEditProfile(): void {
    console.log('Navigating to Edit Profile...');
    // Implement navigation logic here
  }
}

<div class="flex items-center justify-center min-h-screen bg-gradient-to-r from-blue-100 to-green-100">
    <div class="bg-white p-8 rounded-2xl shadow-lg w-full max-w-md">
      <h2 class="text-3xl font-bold text-center text-gray-800 mb-4">Your Profile</h2>
  
      <div *ngIf="error; else profileContent" class="text-red-500 mb-4 text-center">
        {{ error }}
      </div>
  
      <ng-template #profileContent>
        <div class="space-y-4 text-gray-700">
          <div class="flex items-center justify-between">
            <span class="font-semibold">Email:</span>
            <span>{{ user?.userEmail }}</span>
          </div>
          <div class="flex items-center justify-between">
            <span class="font-semibold">Role:</span>
            <span class="capitalize">{{ user?.userRole }}</span>
          </div>
          <div class="flex items-center justify-between">
            <span class="font-semibold">Mobile Number:</span>
            <span>{{ user?.userMobileNum }}</span>
          </div>
          <div class="flex items-center justify-between">
            <span class="font-semibold">Address:</span>
            <span>{{ user?.userAddress }}</span>
          </div>
        </div>
  
        <button
          (click)="handleEditProfile()"
          class="flex items-center justify-center mt-8 w-full bg-indigo-800 text-white p-3 rounded-lg shadow-md hover:bg-indigo-400 transition-colors duration-200"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5 mr-2"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              d="M17.414 2.586a2 2 0 010 2.828l-1.828 1.828-2.828-2.828L14.586 2.586a2 2 0 012.828 0zM4 13l4.586-4.586 2.828 2.828L6.828 15.828H4v-2.828z"
            />
          </svg>
          Edit Profile
        </button>
      </ng-template>
    </div>
  </div>

// frontend/src/pages/profile.tsx
// src/components/Profile.tsx
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { FaUserEdit } from 'react-icons/fa';

const Profile: React.FC = () => {
    const { user } = useAuth();
    const navigate = useNavigate();
    const [error, setError] = useState<string | null>(null);

    if (!user) {
        return <div className="text-center text-lg font-semibold text-gray-600">No user data found.</div>;
    }

    const handleEditProfile = () => {
        try {
            navigate('/editProfile');
        } catch (err) {
            console.error('Error navigating to edit profile:', err);
            setError('Failed to navigate to edit profile.');
        }
    };

    return (
        <div className="flex items-center justify-center min-h-screen bg-gradient-to-r from-blue-100 to-green-100">
            <div className="bg-white p-8 rounded-2xl shadow-lg w-full max-w-md">
                {/* <div className="flex items-center justify-center mb-6">
                    <img
                        src="/path/to/profile-picture.png" // Replace with actual profile image path or user image
                        alt="Profile"
                        className="w-24 h-24 rounded-full shadow-md"
                    />
                </div> */}
                <h2 className="text-3xl font-bold text-center text-gray-800 mb-4">Your Profile</h2>
                {error && <div className="text-red-500 mb-4 text-center">{error}</div>}

                <div className="space-y-4 text-gray-700">
                    <div className="flex items-center justify-between">
                        <span className="font-semibold">Email:</span>
                        <span>{user.userEmail}</span>
                    </div>
                    <div className="flex items-center justify-between">
                        <span className="font-semibold">Role:</span>
                        <span className="capitalize">{user.userRole}</span>
                    </div>
                    <div className="flex items-center justify-between">
                        <span className="font-semibold">Mobile Number:</span>
                        <span>{user.userMobileNum}</span>
                    </div>
                    <div className="flex items-center justify-between">
                        <span className="font-semibold">Address:</span>
                        <span>{user.userAddress}</span>
                    </div>
                </div>

                <button
                    onClick={handleEditProfile}
                    className="flex items-center justify-center mt-8 w-full bg-indigo-800 text-white p-3 rounded-lg shadow-md hover:bg-indigo-400 transition-colors duration-200"
                >
                    <FaUserEdit className="mr-2" />
                    Edit Profile
                </button>
            </div>
        </div>
    );
};

export default Profile;
