// frontend/src/pages/AddTransaction.tsx
import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';

const generateTransactionId = () => {
    return `txn_${Date.now()}_${Math.floor(Math.random() * 10000)}`;
};

const AddTransaction: React.FC = () => {
    const { state } = useLocation();
    const { groupId, userId } = useParams<{ groupId: string; userId: string }>();
    const navigate = useNavigate();
    const [amount, setAmount] = useState<number>(state.ticketValue);
    const [error, setError] = useState<string | null>(null);
    const [organizerId, setOrganizerId] = useState<string | null>(null);

    // Fetch organizer's ID from the Group Service
    useEffect(() => {
        const fetchOrganizer = async () => {
            try {
                const response = await axios.get(`http://localhost:3003/api/groups/getOrganizer/${groupId}`);
                if (response.data.organizerId) {
                    setOrganizerId(response.data.organizerId);
                } else {
                    setError('Organizer not found for this group');
                }
            } catch (error) {
                setError('Failed to fetch organizer ID');
            }
        };

        fetchOrganizer();
    }, [groupId]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Ensure the organizerId is available before submitting
        if (!organizerId) {
            setError('Organizer not found. Please try again later.');
            return;
        }

        const transactionId = generateTransactionId();

        try {
            console.log(userId, groupId, amount, new Date().toISOString(), transactionId, organizerId);
            await axios.post(
                `http://localhost:3000/api/transactions`,
                {
                    transactionId,
                    userId,
                    groupId,
                    transactionAmount: amount,
                    transactionType: 'debit', // Assuming the user is making a payment (debit)
                    transactionDate: new Date().toISOString(),
                    transactionFrom: userId, // Sender is the user making the payment
                    transactionTo: organizerId, // Recipient is the group organizer
                },
                {
                    headers: {
                        'Content-Type': 'application/json',
                        Authorization: `Bearer ${localStorage.getItem('authToken')}`,
                    },
                }
            );
            navigate(-1); // Navigate back after success
        } catch (error) {
            console.error('Error adding transaction:', error);
            setError('Failed to add transaction. Please try again.');
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-gradient-to-r from-blue-100 to-green-100 py-12 px-6">
            <div className="w-full max-w-md bg-white rounded-lg shadow-xl p-8">
                <h2 className="text-3xl font-semibold text-center text-indigo-900 mb-6">Pay Installment</h2>
                <form onSubmit={handleSubmit}>
                    <p className="mb-4 text-gray-700 text-lg">
                        <strong>Month:</strong> {state.monthName}
                    </p>
                    <p className="mb-6 text-gray-700 text-lg">
                        <strong>Ticket Value:</strong> ${state.ticketValue}
                    </p>
                    <label className="block text-gray-600 text-lg mb-2">Amount</label>
                    <input
                        type="number"
                        value={amount}
                        onChange={(e) => setAmount(Number(e.target.value))}
                        className="w-full mb-4 p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400"
                        required
                    />
                    {error && <p className="text-red-500 mb-4 text-center">{error}</p>}
                    <button
                        type="submit"
                        className="w-full bg-indigo-800 text-white py-3 rounded-lg font-medium hover:bg-indigo-600 transition duration-200"
                    >
                        Confirm Payment
                    </button>
                </form>
            </div>
        </div>
    );
};

export default AddTransaction;

// frontend-ang/src/app/add-transaction/add-transaction.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { AuthService } from '../../auth/auth.service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';


@Component({
  selector: 'app-add-transaction',
  imports:[CommonModule, FormsModule],
  templateUrl: './add-transaction.component.html',
  styleUrls: ['./add-transaction.component.css'],
})
export class AddTransactionComponent implements OnInit {
  amount: number = 0;
  error: string | null = null;
  organizerId: string | null = null;
  ticketValue: number = 0;
  monthName: string = '';
  groupId: string | null = null;
  userId: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private http: HttpClient,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    const state = history.state;
    this.ticketValue = state.ticketValue;
    this.monthName = state.monthName;
    this.amount = this.ticketValue;

    this.groupId = this.route.snapshot.paramMap.get('groupId');
    this.userId = this.route.snapshot.paramMap.get('userId');

    if (!this.groupId) {
      this.error = 'Group ID is missing.';
      return;
    }

    this.fetchOrganizer();
  }

  fetchOrganizer(): void {
    this.http
      .get<{ organizerId: string }>(
        `http://localhost:3003/api/groups/getOrganizer/${this.groupId}`
      )
      .subscribe(
        (response) => {
          this.organizerId = response.organizerId;
        },
        (error) => {
          console.error('Failed to fetch organizer ID:', error);
          this.error = 'Failed to fetch organizer ID.';
        }
      );
  }

  handleSubmit(): void {
    if (!this.organizerId) {
      this.error = 'Organizer not found. Please try again later.';
      return;
    }

    const transactionId = `txn_${Date.now()}_${Math.floor(Math.random() * 10000)}`;
    const authToken = this.authService.getToken();

    if (!authToken) {
      this.error = 'Authentication token is missing.';
      return;
    }

    const headers = new HttpHeaders({
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    });

    const transaction = {
      transactionId,
      userId: this.userId,
      groupId: this.groupId,
      transactionAmount: this.amount,
      transactionType: 'debit',
      transactionDate: new Date().toISOString(),
      transactionFrom: this.userId,
      transactionTo: this.organizerId,
    };

    this.http.post(`http://localhost:3000/api/transactions`, transaction, { headers }).subscribe(
      () => {
        this.router.navigate([`/groups/${this.groupId}`]);
      },
      (error) => {
        console.error('Error adding transaction:', error);
        this.error = 'Failed to add transaction. Please try again.';
      }
    );
  }
}


<div class="min-h-screen flex items-center justify-center bg-gradient-to-r from-blue-100 to-green-100 py-12 px-6">
    <div class="w-full max-w-md bg-white rounded-lg shadow-xl p-8">
      <h2 class="text-3xl font-semibold text-center text-indigo-900 mb-6">Pay Installment</h2>
      <form (ngSubmit)="handleSubmit()">
        <p class="mb-4 text-gray-700 text-lg">
          <strong>Month:</strong> {{ monthName }}
        </p>
        <p class="mb-6 text-gray-700 text-lg">
          <strong>Ticket Value:</strong> ${{ ticketValue }}
        </p>
        <label for="amount" class="block text-gray-600 text-lg mb-2">Amount</label>
        <input
          id="amount"
          type="number"
          [(ngModel)]="amount"
          name="amount"
          class="w-full mb-4 p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400"
          required
        />
        <p *ngIf="error" class="text-red-500 mb-4 text-center">{{ error }}</p>
        <button
          type="submit"
          class="w-full bg-indigo-800 text-white py-3 rounded-lg font-medium hover:bg-indigo-600 transition duration-200"
        >
          Confirm Payment
        </button>
      </form>
    </div>
  </div>
